[versions]
loom = "1.1.+"
loom_quiltflower = "1.8.+"
minotaur = "2.6.+"
cursegradle = "2.+"
github_release = "2.+"
machete = "1.+"
grgit = "5.0.+"
blossom = "1.3.+"

minecraft = "1.19.4"
quilt_mappings = "10"
fabric_loader = "0.14.17"
fabric_api = "0.76.0+1.19.4"
mixin_extras = "0.2.0-beta.1"
yet_another_config_lib = "2.4.0"
mod_menu = "6.1.0-rc.1"
hid4java = "0.7.0"
quilt_json5 = "1.0.3"
sodium = "mc1.19.4-0.4.10"
iris = "1.5.2+1.19.4"
immediately_fast = "1.1.10+1.19.4"
sdl2_jni = "2.26.4-4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
mixin_extras = { module = "com.github.llamalad7:mixinextras", version.ref = "mixin_extras" }
yet_another_config_lib = { module = "dev.isxander:yet-another-config-lib", version.ref = "yet_another_config_lib" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
hid4java = { module = "org.hid4java:hid4java", version.ref = "hid4java" }
quilt_json5 = { module = "org.quiltmc:quilt-json5", version.ref = "quilt_json5" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
immediately_fast = { module = "maven.modrinth:immediatelyfast", version.ref = "immediately_fast" }
sdl2_jni = { module = "dev.isxander:sdl2-jni", version.ref = "sdl2_jni" }

test_fabric_loader = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric_loader" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
