[versions]
loom = "1.1.+"
loom_quiltflower = "1.8.+"
minotaur = "2.6.+"
cursegradle = "2.+"
github_release = "2.+"
machete = "1.+"
grgit = "5.0.+"

minecraft = "23w04a"
quilt_mappings = "10"
fabric_loader = "0.14.13"
fabric_api = "0.73.1+1.19.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
